### ISSUE TITLE
How do I install this inside of an existing FontTool VENV?

### ISSUE THREAD

**Issue by fmotion1** [ftCLI/FontFinder#23]
I tried following instructions here: https://www.activestate.com/resources/quick-reads/how-to-manually-install-python-packages/

1. Activate my FontTools VENV
2. cd into the root directory where setup.py is located 
3. Enter: `python setup.py install`

This didn't work and gave me a bunch of depreciation warnings. Is there a proper way to install this that I'm missing? I'd really like to use this helper. 

My FontTools VENV is using Python `3.10.11`. Any help would be fantastic. Thank you for creating this helper tool.

**Comment by ftCLI** [comment]
`python -m pip install .`
